import Image from "next/image";
import {
  ExternalLink,
  GraduationCap,
  Info,
  MessagesSquare,
  Repeat2,
  TrendingUp,
} from "lucide-react";
import { ChalkTrail } from "./chalk-trail";
import { CountUpMetric } from "./count-up-metric";
import { ProposalSectionNav } from "./proposal-section-nav";
import { ReleaseWordMap } from "./release-word-map";
import { ScrollScrubVideo } from "./scroll-scrub-video";
import { PlayableReelCard } from "./playable-reel-card";
import {
  codexOpenClawReel,
  featuredReelSections,
  type FeaturedReel,
} from "./reels";
import { TypedQuestionList } from "./typed-question-list";
import { WhyMichelleStepRail } from "./why-michelle-step-rail";
const heroIntro = [
  "ChatGPT has the power to completely change how people learn, work, create, build, and live.",
  "But most people still don't know how to actually use it.",
  "I want to help change that.",
];
const everydayQuestions = [
  "Can AI help me put this spreadsheet together? How?",
  "Can AI help me prepare for this interview? How?",
  "Can AI help me learn Python? How?",
  "Can AI help me organize my week? How?",
  "Can AI help me make more money? How?",
];
type UseCaseFeature = {
  feature: string;
  featureImage?: string;
  useCases: string[];
};
const chatGPTUseCaseFeatures: UseCaseFeature[] = [
  {
    feature: "Connectors",
    featureImage: "/begin/releases-generated/connectors.png",
    useCases: [
      "How to make a personal income tracker.",
      "How to look through your Granola meetings and update your personal CRM.",
      "How to dig through your emails and find assignments you are losing track of.",
      "How to make a Canva vision board from your saved ideas.",
      "How to make a Spotify playlist for a road trip, a study night, or a GENERATIONAL lock in. (that's 3 😉)",
    ],
  },
  {
    feature: "Codex",
    featureImage: "/begin/releases-generated/codex.png",
    useCases: [
      "How to use Codex to build a portfolio website as an artist, writer, or musician.",
      "How to use Codex to research a health problem that has been bothering you.",
      "How to use Codex to write a full-length book that's 300+ pages. (I have lots of friends with book ideas sitting in their Notes app 😅)",
    ],
  },
  {
    feature: "Memory",
    featureImage: "/begin/releases-generated/memory-dreaming.png",
    useCases: [
      "How to keep track of your daily tasks like a personal assistant.",
      "How to analyze your behavioral patterns and find ways to grow.",
      "How to navigate your workplace culture.",
      "How to reverse-engineer your goals to achieve them faster.",
    ],
  },
];
const proposalPayoffs = [
  {
    title: "Prolong launch impact",
    description:
      "Keep teaching people about each feature long after launch day.",
    Icon: Repeat2,
  },
  {
    title: "Greater feature adoption",
    description:
      "Make the features that matter most to OpenAI easier for Gen Z to discover, understand, and use.",
    Icon: TrendingUp,
  },
  {
    title: "Direct Gen Z insights",
    description:
      "OpenAI gets insights into what Gen Z wants to try and what still confuses them.",
    Icon: MessagesSquare,
  },
  {
    title: "A trusted Gen Z educator",
    description:
      "Give OpenAI one consistent educator Gen Z can recognize and trust.",
    Icon: GraduationCap,
  },
];
const proposalTimelineStages = [
  {
    step: "01",
    title: "Discussion",
    duration: "2 weeks",
    bullets: [
      "Agree on goals, current priority features, KPIs, and what success looks like.",
      "Confirm points of contact, content formats, and publishing rhythm.",
    ],
  },
  {
    step: "02",
    title: "Discovery",
    duration: "3 months",
    bullets: [
      "Test practical use cases through different formats: videos, carousels, and stories.",
      "Learn what Gen Z responds well to and what they are excited to try.",
      "Measure post views, useful engagement, intent to try, and reported use-case trials.",
      "Take one week to review what worked and plan what comes next.",
    ],
  },
  {
    step: "03",
    title: "Delivery",
    duration: "6-month blocks",
    bullets: [
      "Scale what worked in Discovery into 50 practical ChatGPT use cases every six months.",
      "Focus each block on the features and use cases that support OpenAI's current business priorities.",
      "Take two weeks before the next block to review results and adapt the program around new launches and changing priorities.",
    ],
  },
];
const projectionScenarios = [
  {
    metric: "Annual post views",
    conservative: "4M",
    expected: "10M",
    breakout: "25M",
    definition:
      "The total views generated by 100 content pieces across Instagram and TikTok.",
    calculations: {
      conservative: "40K average views × 100 posts = 4M.",
      expected: "100K average views × 100 posts = 10M.",
      breakout: "250K average views × 100 posts = 25M.",
    },
  },
  {
    metric: "Useful engagements",
    conservative: "440K",
    expected: "1.1M",
    breakout: "2.75M",
    definition:
      "The total likes, comments, saves, and shares generated by the program.",
    calculations: {
      conservative: "11% engagement × 4M views = 440K.",
      expected: "11% engagement × 10M views = 1.1M.",
      breakout: "11% engagement × 25M views = 2.75M.",
    },
  },
  {
    metric: "Intent-to-try signals",
    conservative: "100K",
    expected: "300K",
    breakout: "550K",
    definition:
      "Audience actions showing they want to try a use case, such as saves, resource requests, clicks, or comments expressing interest.",
    calculations: {
      conservative: "1K average signals × 100 posts = 100K.",
      expected: "3K average signals × 100 posts = 300K.",
      breakout: "5.5K average signals × 100 posts = 550K.",
    },
  },
  {
    metric: "Reported use-case trials",
    conservative: "30K",
    expected: "150K",
    breakout: "400K",
    northStar: true,
    definition:
      "Measured through comments and other audience responses asking to try the featured use case.",
    calculations: {
      conservative: "300 average comments × 100 posts = 30K.",
      expected: "1.5K average comments × 100 posts = 150K.",
      breakout: "4K average comments × 100 posts = 400K.",
    },
  },
];
function ReelProofRow({
  reels,
  fontClassName,
}: {
  reels: FeaturedReel[];
  fontClassName: string;
}) {
  return (
    <>
      <div
        className={`begin-mobile-carousel grid gap-5 pt-3 ${
          reels.length === 4
            ? "sm:grid-cols-2 lg:grid-cols-4"
            : reels.length === 2
              ? "sm:grid-cols-2"
              : "sm:grid-cols-3"
        }`}
        role="region"
        aria-label="Featured videos. Swipe horizontally on mobile to see more."
        tabIndex={0}
      >
        {reels.map((reel, index) => {
          const hasDestination = Boolean(reel.videoSrc || reel.instagramUrl);
          const cardContent = (
            <>
              <div className="flex items-center justify-between text-xs font-semibold uppercase tracking-[0.14em] text-white/62">
                <span>Reel {String(index + 1).padStart(2, "0")}</span>
                <span>
                  {reel.views
                    ? `${reel.views} views`
                    : reel.likes
                      ? `${reel.likes} likes`
                      : "Add stats"}
                </span>
              </div>
              <div className="grid place-items-center">
                <div className="grid h-20 w-20 place-items-center rounded-full bg-white text-black shadow-[0_0_30px_rgba(255,255,255,0.24)] transition-transform group-hover:scale-105">
                  <span className="ml-1 h-0 w-0 border-y-[14px] border-l-[22px] border-y-transparent border-l-black" />
                </div>
              </div>
              <div className="space-y-3">
                <p
                  className={`${fontClassName} text-4xl leading-none text-white`}
                >
                  {reel.title}
                </p>
                <p className="text-xs font-semibold uppercase tracking-[0.14em] text-white/58">
                  {reel.views || reel.likes || reel.saves
                    ? [
                        reel.views && `${reel.views} views`,
                        reel.likes && `${reel.likes} likes`,
                        reel.saves && `${reel.saves} saves`,
                      ]
                        .filter(Boolean)
                        .join(" · ")
                    : hasDestination
                      ? "Open on Instagram"
                      : "Add reel link"}
                </p>
                {hasDestination && (reel.views || reel.likes || reel.saves) ? (
                  <p className="text-xs font-semibold uppercase tracking-[0.14em] text-white/58">
                    Open on Instagram
                  </p>
                ) : null}
              </div>
            </>
          );
          const posterContent = reel.posterSrc ? (
            <>
              <Image
                src={reel.posterSrc}
                alt={reel.title}
                fill
                className="object-cover"
                sizes="(min-width: 640px) 30vw, calc(100vw - 48px)"
              />
              {reel.instagramUrl ? (
                <span className="absolute right-4 top-4 grid h-10 w-10 place-items-center rounded-full bg-black/70 text-white transition group-hover:bg-white group-hover:text-black">
                  <ExternalLink aria-hidden="true" className="h-5 w-5" />
                </span>
              ) : null}
              {reel.views || reel.likes || reel.saves ? (
                <div className="absolute inset-x-0 bottom-0 bg-black/78 p-4 text-white">
                  <p className="text-xs font-semibold uppercase tracking-[0.1em]">
                    {[
                      reel.views && `${reel.views} views`,
                      reel.likes && `${reel.likes} likes`,
                      reel.saves && `${reel.saves} saves`,
                    ]
                      .filter(Boolean)
                      .join(" · ")}
                  </p>
                </div>
              ) : null}
            </>
          ) : null;
          return (
            <div
              key={reel.title}
              className={`begin-mobile-carousel-card group relative justify-self-center overflow-hidden rounded-[1.35rem] bg-zinc-950 shadow-[0_0_0_1px_rgba(255,255,255,0.18),0_18px_50px_rgba(0,0,0,0.45)] ${
                reel.posterSrc && !reel.videoSrc
                  ? "aspect-[4/5] w-full self-center"
                  : "aspect-[9/16] w-full self-start"
              }`}
            >
              {reel.videoSrc ? (
                <PlayableReelCard reel={reel} />
              ) : reel.posterSrc ? (
                reel.instagramUrl ? (
                  <a
                    href={reel.instagramUrl}
                    target="_blank"
                    rel="noreferrer"
                    aria-label={`Open ${reel.title} on Instagram`}
                    className="block h-full text-white"
                  >
                    {posterContent}
                  </a>
                ) : (
                  <div className="h-full text-white">{posterContent}</div>
                )
              ) : reel.instagramUrl ? (
                <a
                  href={reel.instagramUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="flex h-full flex-col justify-between bg-[radial-gradient(circle_at_30%_20%,rgba(255,255,255,0.14),transparent_32%),linear-gradient(180deg,#141414,#050505)] p-5 text-white"
                >
                  {cardContent}
                </a>
              ) : (
                <div className="flex h-full flex-col justify-between bg-[radial-gradient(circle_at_30%_20%,rgba(255,255,255,0.1),transparent_32%),linear-gradient(180deg,#121212,#050505)] p-5 text-white">
                  {cardContent}
                </div>
              )}
            </div>
          );
        })}
      </div>
      <p
        className={`${fontClassName} begin-mobile-swipe-cue text-right text-xl text-white/58`}
        aria-hidden="true"
      >
        Swipe to see more →
      </p>
    </>
  );
}
export default function ProposalPage({
  emphasisFontClassName,
}: {
  emphasisFontClassName: string;
}) {
  const emailTeamHref = `mailto:michelle@thedriveagency.co,patrick@thedriveagency.co,teresa@thedriveagency.co?subject=${encodeURIComponent("OpenAI × Michelle — Gen Z Product Education")}&body=${encodeURIComponent("Hi Michelle, Patrick, and Teresa,\n\nI’d love to discuss the three-year Gen Z product-education program and its first Discussion and Discovery phases.\n\nWhat would be the best next step?\n\nBest,")}`;
  return (
    <main
      className="begin-openai-page bg-black pt-16 text-white"
      style={{ cursor: "url('/begin/chalk-cursor.png') 12 12, auto" }}
    >
      <ChalkTrail />
      <ProposalSectionNav fontClassName={emphasisFontClassName} />
      <style>
        {`
          @keyframes begin-arrow-bounce {
            0%, 100% {
              transform: translateX(-50%) translateY(0);
            }
            50% {
              transform: translateX(-50%) translateY(12px);
            }
          }

          @keyframes begin-type-line {
            from {
              clip-path: inset(0 100% 0 0);
            }
            to {
              clip-path: inset(0 0 0 0);
            }
          }

          @keyframes begin-chalk-strike {
            from {
              clip-path: inset(0 100% 0 0);
              opacity: 0;
            }
            12% {
              opacity: 1;
            }
            to {
              clip-path: inset(0 0 0 0);
              opacity: 1;
            }
          }

          .begin-why-michelle-sticky .begin-codex-pet-lane {
            width: 100%;
            min-width: 0;
            flex: none;
          }

          @keyframes begin-why-michelle-story-focus {
            0%, 100% {
              opacity: 0.12;
              filter: blur(7px);
              transform: translateY(3rem) scale(0.975);
            }
            28%, 72% {
              opacity: 1;
              filter: blur(0);
              transform: translateY(0) scale(1);
            }
          }

          @keyframes begin-codex-travel {
            0% {
              left: 0;
              opacity: 0;
              transform: scaleX(1);
            }
            3% {
              opacity: 1;
            }
            43% {
              left: calc(100% - var(--mia-w));
              opacity: 1;
              transform: scaleX(1);
            }
            43.01%, 49% {
              left: calc(100% - var(--mia-w));
              opacity: 1;
              transform: scaleX(-1);
            }
            89% {
              left: 0;
              opacity: 1;
              transform: scaleX(-1);
            }
            89.01%, 96% {
              left: 0;
              opacity: 1;
              transform: scaleX(1);
            }
            100% {
              left: 0;
              opacity: 0;
              transform: scaleX(1);
            }
          }

          @keyframes begin-mia-loop {
            0%, 5%, 50%, 55% {
              background-position: 0 calc(var(--mia-h) * -1);
              transform: translateY(0);
            }
            6%, 10%, 56%, 60% {
              background-position: calc(var(--mia-w) * -1) calc(var(--mia-h) * -1);
            }
            11%, 15%, 61%, 65% {
              background-position: calc(var(--mia-w) * -2) calc(var(--mia-h) * -1);
            }
            16%, 20%, 66%, 70% {
              background-position: calc(var(--mia-w) * -3) calc(var(--mia-h) * -1);
            }
            21%, 25%, 71%, 75% {
              background-position: calc(var(--mia-w) * -4) calc(var(--mia-h) * -1);
            }
            26%, 30%, 76%, 80% {
              background-position: calc(var(--mia-w) * -5) calc(var(--mia-h) * -1);
            }
            31%, 35%, 81%, 85% {
              background-position: calc(var(--mia-w) * -6) calc(var(--mia-h) * -1);
            }
            36%, 42%, 86%, 89% {
              background-position: calc(var(--mia-w) * -7) calc(var(--mia-h) * -1);
            }
            43%, 49%, 90%, 100% {
              background-position: calc(var(--mia-w) * -6) 0;
              transform: translateY(0);
            }
          }

          @keyframes begin-codex-hover-emote {
            0%, 100% {
              background-position: 0 calc(var(--mia-h) * -3);
              transform: translateY(0);
            }
            20% {
              background-position: calc(var(--mia-w) * -1) calc(var(--mia-h) * -3);
            }
            40% {
              background-position: calc(var(--mia-w) * -2) calc(var(--mia-h) * -3);
              transform: translateY(-0.15rem);
            }
            60% {
              background-position: calc(var(--mia-w) * -3) calc(var(--mia-h) * -3);
            }
            80% {
              background-position: calc(var(--mia-w) * -4) calc(var(--mia-h) * -3);
              transform: translateY(0);
            }
          }

          .begin-codex-pet-lane {
            --mia-w: clamp(5rem, 8vw, 6.75rem);
            --mia-h: calc(var(--mia-w) * 1.083333);
            position: relative;
            min-width: 12rem;
            height: calc(var(--mia-h) + 0.8rem);
            flex: 1 1 16rem;
            overflow: hidden;
          }

          .begin-codex-pet-traveler {
            position: absolute;
            bottom: 0;
            left: 0;
            width: var(--mia-w);
            height: var(--mia-h);
            transform-origin: center;
            animation: begin-codex-travel 9s linear infinite;
          }

          .begin-mia-sprite {
            width: var(--mia-w);
            height: var(--mia-h);
            background-image: url('/begin/codex-default-spritesheet.webp');
            background-repeat: no-repeat;
            background-size: calc(var(--mia-w) * 8) calc(var(--mia-h) * 11);
            background-position: calc(var(--mia-w) * -6) 0;
            image-rendering: auto;
            filter: drop-shadow(0 0 18px rgba(255,255,255,0.16));
            animation: begin-mia-loop 9s steps(1, end) infinite;
          }

          .begin-codex-pet-lane:hover .begin-codex-pet-traveler {
            animation-play-state: paused;
          }

          .begin-codex-pet-lane:hover .begin-mia-sprite {
            animation: begin-codex-hover-emote 1.25s steps(1, end) infinite;
          }

          .begin-typing-group {
            width: max-content;
            max-width: 100%;
            text-align: center;
          }

          .begin-typing-line {
            display: block;
            width: 100%;
            max-width: 100%;
            white-space: nowrap;
            clip-path: inset(0 100% 0 0);
            animation: begin-type-line 1.18s steps(92, end) forwards;
          }

          .begin-typing-line:nth-child(2) {
            animation-delay: 1.02s;
          }

          .begin-typing-line:nth-child(3) {
            animation-delay: 1.92s;
          }

          .begin-typing-line:nth-child(4) {
            animation-delay: 2.82s;
          }

          .begin-chalk-strike {
            display: flex;
            flex-direction: column;
            align-items: flex-start;
            width: fit-content;
          }

          .begin-chalk-strike-line {
            position: relative;
            display: block;
            width: fit-content;
          }

          .begin-chalk-strike-line::after {
            content: "";
            position: absolute;
            left: -0.08em;
            right: -0.08em;
            top: 50%;
            height: 0.16em;
            pointer-events: none;
            background:
              linear-gradient(180deg, transparent 0 18%, rgba(255,255,255,0.94) 24% 68%, transparent 78%),
              repeating-linear-gradient(90deg, rgba(255,255,255,0.88) 0 7px, rgba(255,255,255,0.55) 7px 11px, rgba(255,255,255,0.9) 11px 18px);
            box-shadow:
              0 -1px 0 rgba(255,255,255,0.36),
              0 1px 0 rgba(255,255,255,0.28),
              0 0 4px rgba(255,255,255,0.24);
            clip-path: inset(0 100% 0 0);
            animation: begin-chalk-strike 0.72s steps(22, end) 500ms forwards;
          }

          .begin-chalk-strike-line:nth-child(2)::after {
            animation-delay: 1.08s;
          }

          .begin-chalk-strike-mobile {
            display: none;
          }

          .begin-mobile-swipe-cue {
            display: none;
          }

          .begin-email-team-button {
            position: relative;
            display: flex;
            width: min(100%, 58rem);
            aspect-ratio: 3 / 1;
            align-items: center;
            justify-content: center;
            padding: 2rem 4rem 2.3rem;
            color: rgba(255,255,255,0.92);
            text-align: center;
            text-decoration: none;
            background-image: url('/begin/generated/email-team-chalk-bevel-erased.png');
            background-position: center;
            background-repeat: no-repeat;
            background-size: contain;
            filter: drop-shadow(0 12px 22px rgba(0,0,0,0.4));
            transform: rotate(-0.35deg);
            transition: transform 180ms ease, color 180ms ease, filter 180ms ease;
          }

          .begin-email-team-button:hover {
            color: white;
            transform: rotate(0deg) translateY(-3px) scale(1.012);
            filter: drop-shadow(0 16px 28px rgba(0,0,0,0.55)) brightness(1.08);
          }

          .begin-email-team-button:focus-visible {
            outline: 3px solid white;
            outline-offset: 7px;
          }

          @media (max-width: 639px) {
            .begin-email-team-button {
              padding: 1rem 2rem 1.15rem;
            }
          }

          @supports (animation-timeline: view()) {
            .begin-chalk-strike-line::after {
              animation-delay: 0ms;
              animation-timeline: view();
              animation-range: entry 68% contain 80%;
            }

            .begin-chalk-strike-line:nth-child(2)::after {
              animation-range: entry 80% contain 95%;
            }

            .begin-why-michelle-story {
              animation: begin-why-michelle-story-focus linear both;
              animation-timeline: view();
              animation-range: entry 0% exit 100%;
            }
          }

          @media (max-width: 900px) {
            .begin-typing-group {
              width: auto;
            }

            .begin-typing-line {
              width: auto;
              max-width: none;
              white-space: normal;
              clip-path: none;
              animation: none;
            }
          }

          @media (max-width: 639px) {
            .begin-openai-page {
              cursor: auto !important;
              overflow-x: clip;
            }

            .begin-mobile-intro-grid {
              grid-template-columns: minmax(0, 1fr);
              width: 100%;
              min-width: 0;
            }

            .begin-mobile-intro-grid > *,
            .begin-mobile-intro-copy {
              width: 100%;
              min-width: 0;
              max-width: 100%;
            }

            .begin-why-michelle-story {
              animation: none !important;
              opacity: 1 !important;
              filter: none !important;
              transform: none !important;
            }

            .begin-mia-sprite {
              filter: drop-shadow(0 0 12px rgba(255,255,255,0.14));
            }

            .begin-codex-pet-lane {
              --mia-w: 4.75rem;
              min-width: 9rem;
              flex-basis: 10rem;
            }

            .begin-mobile-carousel,
            .begin-mobile-comment-carousel {
              display: flex;
              width: auto;
              margin-right: -1.5rem;
              padding-right: 1.5rem;
              overflow-x: auto;
              overflow-y: hidden;
              overscroll-behavior-inline: contain;
              scroll-snap-type: x mandatory;
              scrollbar-width: none;
              -webkit-overflow-scrolling: touch;
            }

            .begin-mobile-carousel::-webkit-scrollbar,
            .begin-mobile-comment-carousel::-webkit-scrollbar {
              display: none;
            }

            .begin-mobile-carousel-card {
              width: min(76vw, 18rem) !important;
              min-width: min(76vw, 18rem);
              flex: 0 0 min(76vw, 18rem);
              scroll-snap-align: start;
            }

            .begin-mobile-swipe-cue {
              display: block;
              margin-top: 0.75rem;
            }

            .begin-mobile-comment-carousel > * {
              width: min(80vw, 20rem) !important;
              min-width: min(80vw, 20rem);
              flex: 0 0 min(80vw, 20rem);
              scroll-snap-align: start;
              align-self: flex-start;
            }

            .begin-chalk-strike-desktop {
              display: none;
            }

            .begin-chalk-strike-mobile {
              display: flex;
            }

            .begin-chalk-strike-line:nth-child(3)::after {
              animation-delay: 1.66s;
            }
          }

          @media (prefers-reduced-motion: reduce) {
            .begin-mia-sprite,
            .begin-codex-pet-traveler {
              animation: none;
            }

            .begin-why-michelle-story {
              animation: none;
              opacity: 1;
              transform: none;
            }

            .begin-codex-pet-traveler {
              left: 0;
              opacity: 1;
            }
          }

          @media (max-width: 639px) and (prefers-reduced-motion: reduce) {
            .begin-typing-line,
            .begin-chalk-strike-line::after {
              animation: none;
              clip-path: none;
            }

            .begin-openai-arrow {
              animation: none;
            }
          }
        `}
      </style>
      <section className="relative min-h-[calc(100vh-4rem)] bg-black px-6 py-8 sm:px-10 lg:px-16">
        <div className="mx-auto flex min-h-[calc(100vh-8rem)] max-w-6xl flex-col justify-start">
          <div className="relative mx-auto flex max-w-5xl flex-1 flex-col items-center justify-start pb-24 pt-10 text-center sm:pb-28 sm:pt-20 lg:pt-24">
            <Image
              src="/begin/chalk-heart.png"
              alt=""
              width={220}
              height={220}
              aria-hidden="true"
              className="absolute right-2 top-20 h-16 w-16 rotate-12 opacity-55 sm:-right-8 sm:top-14 sm:h-24 sm:w-24 lg:-right-12 lg:h-28 lg:w-28"
            />
            <h1
              className={`${emphasisFontClassName} relative max-w-5xl text-5xl font-normal leading-[0.95] sm:text-8xl lg:text-9xl`}
            >
              Teaching the Next Generation How to Use AI
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-base leading-7 text-white/74 sm:mt-7 sm:text-xl sm:leading-8">
              A proposal for an ongoing educational partnership between Michelle
              Lawson (
              <a
                href="https://www.instagram.com/michellescomputer/"
                target="_blank"
                rel="noreferrer"
                className="underline decoration-white/35 underline-offset-4 transition hover:text-white hover:decoration-white"
              >
                @michellescomputer
              </a>
              ) and OpenAI.
            </p>
            <div className="begin-typing-group mx-auto mt-8 space-y-3 text-base leading-7 text-white/72 sm:mt-10 sm:space-y-4 sm:text-xl sm:leading-8">
              {heroIntro.map((line, index) => (
                <p className="begin-typing-line" key={line}>
                  {index === heroIntro.length - 1 ? (
                    <a
                      href="#the-proposal"
                      aria-label="Here's how: jump to the proposal"
                      className="group inline-grid rounded-sm font-semibold text-white transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/70 focus-visible:ring-offset-4 focus-visible:ring-offset-black"
                    >
                      <span className="col-start-1 row-start-1 transition-all duration-200 group-hover:-translate-y-1 group-hover:opacity-0 group-focus-visible:-translate-y-1 group-focus-visible:opacity-0">
                        {line}
                      </span>
                      <span
                        aria-hidden="true"
                        className="col-start-1 row-start-1 translate-y-1 opacity-0 transition-all duration-200 group-hover:translate-y-0 group-hover:opacity-100 group-focus-visible:translate-y-0 group-focus-visible:opacity-100"
                      >
                        Here&apos;s how →
                      </span>
                    </a>
                  ) : (
                    line
                  )}
                </p>
              ))}
            </div>
          </div>
        </div>
        <Image
          src="/begin/chalk-down-arrow.png"
          alt=""
          width={160}
          height={160}
          aria-hidden="true"
          className="begin-openai-arrow absolute bottom-0 left-1/2 h-24 w-24 -translate-x-1/2 animate-[begin-arrow-bounce_1.7s_ease-in-out_infinite] opacity-85 sm:bottom-1 sm:h-40 sm:w-40"
        />
      </section>

      <section
        id="introduction"
        className="scroll-mt-20 bg-black px-6 py-16 sm:px-10 sm:py-24 lg:px-16 lg:pb-20 lg:pt-32"
      >
        <div className="begin-mobile-intro-grid mx-auto grid max-w-6xl items-center gap-14 lg:grid-cols-[0.82fr_1.18fr] lg:items-start lg:gap-20">
          <div className="relative mx-auto w-full max-w-[19rem] sm:max-w-md lg:sticky lg:top-24 lg:max-w-none lg:self-start">
            <div
              className="aspect-[4/5] overflow-hidden"
              style={{
                WebkitMaskImage: "url('/begin/michelle-blob-mask.svg')",
                maskImage: "url('/begin/michelle-blob-mask.svg')",
                WebkitMaskPosition: "center",
                maskPosition: "center",
                WebkitMaskRepeat: "no-repeat",
                maskRepeat: "no-repeat",
                WebkitMaskSize: "100% 100%",
                maskSize: "100% 100%",
              }}
            >
              <Image
                src="/begin/michelle-portrait.jpeg"
                alt="Michelle Lawson looking directly at the camera"
                width={768}
                height={1024}
                className="h-full w-full object-cover"
                sizes="(min-width: 1024px) 430px, (min-width: 640px) 448px, calc(100vw - 48px)"
              />
            </div>
          </div>

          <div className="begin-mobile-intro-copy space-y-9 sm:space-y-12">
            <div className="space-y-5">
              <h2
                className={`${emphasisFontClassName} text-[3.5rem] font-normal leading-none sm:text-8xl`}
              >
                Hi, I&apos;m Michelle.
              </h2>
              <p className="max-w-2xl text-xl leading-9 text-white/72">
                I teach Gen Z how to use computer science and AI to gain agency,
                turn their ideas into reality, and create more possibilities for
                themselves.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-x-6 gap-y-8 sm:grid-cols-3 sm:gap-5">
              <div className="space-y-3">
                <Image
                  src="/begin/about-stats/250k.png"
                  alt="250K plus"
                  width={1553}
                  height={436}
                  className="h-14 w-auto max-w-full object-contain object-left sm:h-16 lg:h-20"
                  sizes="(min-width: 1024px) 190px, (min-width: 640px) 160px, 280px"
                />
                <p className="text-base leading-6 text-white/68">
                  followers across platforms
                </p>
              </div>
              <div className="space-y-3">
                <Image
                  src="/begin/about-stats/millions.png"
                  alt="Millions"
                  width={1682}
                  height={430}
                  className="h-14 w-auto max-w-full object-contain object-left sm:h-16 lg:h-20"
                  sizes="(min-width: 1024px) 210px, (min-width: 640px) 170px, 300px"
                />
                <p className="text-base leading-6 text-white/68">
                  of video views
                </p>
              </div>
              <details className="group relative col-span-2 sm:col-span-1">
                <summary
                  className="space-y-3 list-none cursor-help rounded-sm outline-none focus-visible:ring-2 focus-visible:ring-white/80 focus-visible:ring-offset-4 focus-visible:ring-offset-black [&::-webkit-details-marker]:hidden"
                  aria-label="Show the industry engagement-rate comparison"
                  title="See the industry comparison"
                >
                  <Image
                    src="/begin/about-stats/11-percent.png"
                    alt="11 percent"
                    width={1202}
                    height={673}
                    className="h-14 w-auto max-w-full object-contain object-left sm:h-16 lg:h-20"
                    sizes="(min-width: 1024px) 150px, (min-width: 640px) 125px, 210px"
                  />
                  <p className="text-base leading-6 text-white/68 underline decoration-white/25 decoration-dotted underline-offset-4 transition group-hover:text-white">
                    Instagram engagement by reach
                    <span
                      aria-hidden="true"
                      className="ml-1.5 inline-grid h-6 w-6 place-items-center align-middle bg-[url('/begin/generated/chalk-nav-circle.png')] bg-contain bg-center bg-no-repeat text-white/85 opacity-80 transition group-hover:scale-105 group-hover:opacity-100 group-open:opacity-100"
                    >
                      <Info className="h-3 w-3" strokeWidth={2.4} />
                    </span>
                  </p>
                </summary>
                <div
                  role="tooltip"
                  className="invisible absolute left-1/2 top-full z-50 mt-3 w-72 max-w-[calc(100vw-3rem)] -translate-x-1/2 rounded border border-white/25 bg-black px-4 py-3 text-sm leading-6 text-white/78 opacity-0 shadow-[0_12px_30px_rgba(0,0,0,0.55)] transition group-open:visible group-open:opacity-100 group-hover:visible group-hover:opacity-100 group-focus-within:visible group-focus-within:opacity-100"
                >
                  Compared to an{" "}
                  <a
                    href="https://blog.hootsuite.com/average-engagement-rate/"
                    target="_blank"
                    rel="noreferrer"
                    className="font-semibold text-white underline decoration-white/50 underline-offset-4 hover:decoration-white"
                  >
                    industry average of 3.3%
                  </a>
                  .
                </div>
              </details>
            </div>

            <div className="space-y-7 text-xl leading-9 text-white/72">
              <p>
                {
                  "I've partnered with OpenAI over the past year to make new features feel practical, exciting, and worth trying."
                }
              </p>

              <div className="mx-auto max-w-[34rem]">
                <ReelProofRow
                  fontClassName={emphasisFontClassName}
                  reels={[
                    ...featuredReelSections[2].reels.filter(
                      (reel) => reel.videoSrc,
                    ),
                    codexOpenClawReel,
                  ]}
                />
              </div>

              <p className="text-white">
                {
                  "But the more I work with OpenAI, the more I realize that the biggest opportunity is teaching people what to actually do with your products."
                }
              </p>
            </div>
          </div>
        </div>
      </section>

      {
        <section
          id="the-opportunity"
          className="scroll-mt-20 bg-black px-6 py-16 sm:px-10 sm:pb-16 sm:pt-24 lg:px-16"
        >
          <div className="mx-auto max-w-6xl space-y-16">
            <div className="relative max-w-5xl">
              <h2
                className={`${emphasisFontClassName} relative z-10 max-w-4xl text-5xl font-normal leading-none tracking-tight sm:text-8xl`}
              >
                {
                  "Every few weeks, OpenAI releases something that blows my mind."
                }
              </h2>
              <Image
                src="/begin/messy-math-papers.png"
                alt=""
                width={1402}
                height={1122}
                aria-hidden="true"
                className="pointer-events-none absolute -right-12 top-8 z-0 hidden w-52 rotate-6 opacity-62 lg:block xl:-right-24 xl:w-60"
                sizes="240px"
              />
            </div>

            <ReleaseWordMap
              assets={undefined}
              fontClassName={emphasisFontClassName}
              ariaLabel="Recent OpenAI releases"
            />

            <div className="mx-auto max-w-4xl space-y-7 pt-8 text-xl leading-9 text-white/72 sm:pt-12">
              <p>And every single time, I run into the same problem.</p>
              <p className="text-2xl font-semibold leading-9 text-white">
                I only get to make one or two videos.
              </p>
              <p>
                {
                  "One or two chances to explain dozens of incredible features, possibilities, and ideas."
                }
              </p>
              <p>
                {
                  "But I know the most memorable posts must have one simple core idea, so people walk away with something to try."
                }
              </p>
              <p>So I constantly find myself asking:</p>
            </div>

            <div className="mx-auto max-w-5xl py-4 text-center sm:py-6">
              <p className="mx-auto max-w-3xl text-xl leading-9 text-white/68">
                &quot; Which possibilities am I leaving out? &quot;
              </p>
              <p
                className={`${emphasisFontClassName} mx-auto mt-6 max-w-5xl text-4xl font-normal leading-none text-white sm:text-[3.25rem]`}
              >
                There are simply too many good use cases for one video.
              </p>
            </div>

            {
              <div className="mx-auto max-w-4xl space-y-7 text-xl leading-9 text-white/72">
                <p>
                  {
                    "Maybe the goal isn't to fit everything into one video, or even one influencer campaign sprint."
                  }
                </p>
                <p
                  className={`${emphasisFontClassName} py-8 text-4xl font-normal leading-none text-white sm:text-6xl`}
                >
                  The goal is to educate people over time.
                </p>
                <p>
                  Because education is the highest form of product leverage.
                </p>
                <p>
                  <strong>So let's teach people!</strong>
                </p>
              </div>
            }
          </div>
        </section>
      }

      <section
        id="why-educate"
        className="scroll-mt-20 bg-black px-6 py-16 sm:px-10 sm:pb-24 sm:pt-16 lg:px-16"
      >
        <div className="mx-auto max-w-5xl space-y-14">
          {
            <>
              <div className="space-y-7">
                <h2
                  className={`${emphasisFontClassName} text-3xl font-normal leading-none tracking-tight sm:text-7xl`}
                >
                  Nobody wakes up thinking,
                </h2>
                <div
                  className="text-2xl leading-tight text-white/86 sm:text-4xl"
                  aria-label={
                    "I really hope I get to use frontier reasoning today."
                  }
                >
                  <p
                    className="begin-chalk-strike begin-chalk-strike-desktop"
                    aria-hidden="true"
                  >
                    <span className="begin-chalk-strike-line">
                      &quot;I really hope I get to use
                    </span>
                    <span className="begin-chalk-strike-line">
                      {'frontier reasoning today."'}
                    </span>
                  </p>
                  <p
                    className="begin-chalk-strike begin-chalk-strike-mobile"
                    aria-hidden="true"
                  >
                    <span className="begin-chalk-strike-line">
                      &quot;I really hope I get
                    </span>
                    <span className="begin-chalk-strike-line">
                      to use frontier reasoning
                    </span>
                    <span className="begin-chalk-strike-line">{'today."'}</span>
                  </p>
                </div>
              </div>

              <div className="space-y-5">
                <p className="text-xl leading-9 text-white/72">
                  They wake up thinking,
                </p>
                <TypedQuestionList
                  questions={everydayQuestions}
                  fontClassName={emphasisFontClassName}
                />
              </div>

              <div className="relative left-1/2 min-h-[28rem] w-[min(76rem,calc(100vw-3rem))] -translate-x-1/2 overflow-hidden sm:min-h-[36rem]">
                <Image
                  src="/begin/michelle-photos/michelle-speaking-pink-scarf.jpeg"
                  alt="Michelle Lawson speaking into a microphone while teaching"
                  fill
                  className="object-cover object-[62%_center] sm:object-center"
                  sizes="(min-width: 1280px) 1216px, calc(100vw - 48px)"
                />
                <div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/42 to-transparent" />
                <div className="absolute inset-0 flex items-center px-7 sm:px-14 lg:px-20">
                  <p
                    className={`${emphasisFontClassName} max-w-[11ch] text-5xl font-normal leading-none text-white drop-shadow-[0_3px_12px_rgba(0,0,0,0.8)] sm:text-8xl`}
                  >
                    That's where I come in,
                  </p>
                </div>
              </div>

              <div className="mx-auto max-w-4xl space-y-7 text-xl leading-9 text-white/72">
                <p className="mx-auto max-w-3xl text-center text-2xl leading-9 text-white/88 sm:text-[2rem] sm:leading-10">
                  {
                    "a dedicated educator who teaches people what to do with all OpenAI's brilliant tools."
                  }
                </p>
                <p className="mx-auto max-w-3xl text-center">
                  I will turn your features into relevant lessons{" "}
                  <strong>Gen Z will understand, try, and come to love.</strong>
                </p>
              </div>
            </>
          }

          <div
            id="why-michelle"
            className="relative left-1/2 w-[min(72rem,calc(100vw-3rem))] -translate-x-1/2 scroll-mt-20"
          >
            <div className="mb-14 flex flex-wrap items-end gap-5 sm:flex-nowrap sm:gap-7 lg:hidden">
              <h2
                className={`${emphasisFontClassName} text-6xl font-normal leading-none tracking-tight text-white sm:text-8xl`}
              >
                Why Michelle?
              </h2>
              <div
                className="begin-codex-pet-lane"
                role="img"
                aria-label={
                  "Animated Codex pet walking back and forth beside the Why Michelle heading"
                }
              >
                <div className="begin-codex-pet-traveler" aria-hidden="true">
                  <div className="begin-mia-sprite" />
                </div>
              </div>
            </div>

            <div className="grid items-start lg:grid-cols-[19rem_minmax(0,1fr)] lg:gap-14">
              <aside className="begin-why-michelle-sticky sticky top-20 hidden h-[calc(100vh-5rem)] flex-col justify-center lg:flex">
                <h2
                  className={`${emphasisFontClassName} text-7xl font-normal leading-none tracking-tight text-white`}
                >
                  Why Michelle?
                </h2>
                <div
                  className="begin-codex-pet-lane mt-5"
                  role="img"
                  aria-label={
                    "Animated Codex pet walking back and forth beside the Why Michelle heading"
                  }
                >
                  <div className="begin-codex-pet-traveler" aria-hidden="true">
                    <div className="begin-mia-sprite" />
                  </div>
                </div>
                <WhyMichelleStepRail />
              </aside>

              <div className="min-w-0 max-w-4xl space-y-14 text-xl leading-9 text-white/72 sm:space-y-20 lg:space-y-0">
                <div
                  id="why-michelle-point-1"
                  className="begin-why-michelle-story scroll-mt-24 space-y-7 lg:min-h-screen lg:py-20 lg:pr-4"
                >
                  <div className="flex items-start gap-4 sm:items-center">
                    <Image
                      src="/begin/chalk-numbers/chalk-circled-1.png"
                      alt="1"
                      width={512}
                      height={512}
                      className="mt-1 h-12 w-12 shrink-0 object-contain sm:mt-0 sm:h-14 sm:w-14 lg:hidden"
                    />
                    <h3
                      className={`${emphasisFontClassName} text-[2rem] leading-none text-white sm:text-5xl`}
                    >
                      I make complicated concepts simple
                    </h3>
                  </div>
                  <p className="text-xl leading-8 text-white sm:text-2xl sm:leading-9">
                    I make new concepts useful to my audience by connecting them
                    to ideas they are already familiar with.
                  </p>
                  <p>
                    I started my online presence by making computer science
                    concepts digestible. As I expanded into teaching AI and
                    showing how it can be useful, I kept the same core
                    principles: explain ideas step by step, make every video
                    easy to understand, and ensure viewers walk away with
                    practical knowledge they can use.
                  </p>
                  <ReelProofRow
                    reels={featuredReelSections[0].reels}
                    fontClassName={emphasisFontClassName}
                  />
                  <div
                    className="begin-mobile-comment-carousel grid items-start gap-3 pt-2 sm:grid-cols-2 lg:grid-cols-3"
                    role="region"
                    aria-label="Audience comments. Swipe horizontally on mobile to see more."
                    tabIndex={0}
                  >
                    {[
                      {
                        src: "/begin/comments/agentic-ai-understanding.png",
                        alt: "Audience comment praising the explanation of AI and agentic models",
                        width: 562,
                        height: 168,
                      },
                      {
                        src: "/begin/comments/best-video-on-topic.png",
                        alt: "Audience comment calling it one of the best videos on the topic",
                        width: 574,
                        height: 172,
                      },
                      {
                        src: "/begin/comments/vibe-code-explanation.png",
                        alt: "Audience comment praising the vibe coding explanation",
                        width: 558,
                        height: 164,
                      },
                      {
                        src: "/begin/comments/enlightening-video.png",
                        alt: "Audience comment describing the video as enlightening",
                        width: 568,
                        height: 128,
                      },
                      {
                        src: "/begin/comments/beginner-coding-request.png",
                        alt: "Audience comment asking for more beginner coding education",
                        width: 794,
                        height: 182,
                      },
                    ].map((comment) => (
                      <Image
                        key={comment.src}
                        src={comment.src}
                        alt={comment.alt}
                        width={comment.width}
                        height={comment.height}
                        className="h-auto w-full"
                        sizes="(min-width: 1024px) 250px, (min-width: 768px) 390px, calc(100vw - 48px)"
                      />
                    ))}
                  </div>
                </div>

                <div
                  id="why-michelle-point-2"
                  className="begin-why-michelle-story scroll-mt-24 space-y-7 lg:min-h-screen lg:py-20 lg:pr-4"
                >
                  <div className="flex items-start gap-4 sm:items-center">
                    <Image
                      src="/begin/chalk-numbers/chalk-circled-2.png"
                      alt="2"
                      width={512}
                      height={512}
                      className="mt-1 h-12 w-12 shrink-0 object-contain sm:mt-0 sm:h-14 sm:w-14 lg:hidden"
                    />
                    <h3
                      className={`${emphasisFontClassName} text-[2rem] leading-none text-white sm:text-5xl`}
                    >
                      I keep it engaging for Gen Z
                    </h3>
                  </div>
                  <p className="text-xl leading-8 text-white sm:text-2xl sm:leading-9">
                    250K+ followers across platforms. Millions of video views.
                    An 11% Instagram engagement rate by reach.
                  </p>
                  <p className="text-xl leading-8 text-white sm:text-2xl sm:leading-9">
                    The numbers speak for themselves. The philosophy that led me
                    here is simple:
                    <em>
                      people learn so much more when ideas are presented in a
                      fun and engaging way.
                    </em>
                  </p>
                  <p>
                    My audience loves the variety in my content, whether
                    it&apos;s my challenge videos, inspiring stories, or tech
                    news. Because I speak fluent Gen Z, I keep them captivated
                    with memes, jokes, and nostalgic references. Basically,
                    we&apos;re always joking together while we learn.
                  </p>
                  <ReelProofRow
                    reels={featuredReelSections[1].reels}
                    fontClassName={emphasisFontClassName}
                  />
                  <div
                    className="begin-mobile-comment-carousel grid items-start gap-3 pt-2 sm:grid-cols-2"
                    role="region"
                    aria-label="Audience comments. Swipe horizontally on mobile to see more."
                    tabIndex={0}
                  >
                    {[
                      {
                        src: "/begin/comments/positive-growth-impact.png",
                        alt: "Audience comment describing the positive impact of Michelle's content",
                        width: 812,
                        height: 128,
                      },
                      {
                        src: "/begin/comments/audience-trust-following.png",
                        alt: "Audience comment expressing trust and love for Michelle's content",
                        width: 872,
                        height: 148,
                      },
                    ].map((comment) => (
                      <Image
                        key={comment.src}
                        src={comment.src}
                        alt={comment.alt}
                        width={comment.width}
                        height={comment.height}
                        className="h-auto w-full"
                        sizes="(min-width: 768px) 390px, calc(100vw - 48px)"
                      />
                    ))}
                  </div>
                </div>

                <div
                  id="why-michelle-point-3"
                  className="begin-why-michelle-story scroll-mt-24 space-y-7 lg:min-h-screen lg:py-20 lg:pr-4"
                >
                  <div className="flex items-start gap-4 sm:items-center">
                    <Image
                      src="/begin/chalk-numbers/chalk-circled-3.png"
                      alt="3"
                      width={512}
                      height={512}
                      className="mt-1 h-12 w-12 shrink-0 object-contain sm:mt-0 sm:h-14 sm:w-14 lg:hidden"
                    />
                    <h3
                      className={`${emphasisFontClassName} text-[2rem] leading-none text-white sm:text-5xl`}
                    >
                      I&apos;ve helped people discover OpenAI
                    </h3>
                  </div>
                  <p>
                    {
                      "I've already partnered with OpenAI, translated product launches into useful creator content, and participated in ChatGPT Futures."
                    }
                  </p>
                  <p className="text-xl leading-8 text-white sm:text-2xl sm:leading-9">
                    {
                      "I understand both the products and the audience response that turns a launch into sustained interest."
                    }
                  </p>
                  <ReelProofRow
                    reels={featuredReelSections[2].reels}
                    fontClassName={emphasisFontClassName}
                  />
                  <div
                    className="begin-mobile-comment-carousel grid items-start gap-3 pt-2 sm:grid-cols-2 lg:grid-cols-3"
                    role="region"
                    aria-label="Audience comments. Swipe horizontally on mobile to see more."
                    tabIndex={0}
                  >
                    {[
                      {
                        src: "/begin/comments/codex-automations-discovery.png",
                        alt: "Audience comment discovering Codex automations",
                        width: 976,
                        height: 122,
                      },
                      {
                        src: "/begin/comments/codex-need-to-jump-on.png",
                        alt: "Audience comment saying they need to start using Codex",
                        width: 402,
                        height: 100,
                      },
                      {
                        src: "/begin/comments/codex-sites-automation-question.png",
                        alt: "Audience question about using Codex to update sites automatically",
                        width: 530,
                        height: 202,
                      },
                    ].map((comment) => (
                      <Image
                        key={comment.src}
                        src={comment.src}
                        alt={comment.alt}
                        width={comment.width}
                        height={comment.height}
                        className="h-auto w-full"
                        sizes="(min-width: 1024px) 250px, (min-width: 768px) 390px, calc(100vw - 48px)"
                      />
                    ))}
                  </div>
                </div>

                <div
                  id="why-michelle-point-4"
                  className="begin-why-michelle-story scroll-mt-24 space-y-7 lg:flex lg:min-h-screen lg:flex-col lg:justify-center lg:py-20 lg:pr-4"
                >
                  <div className="flex items-start gap-4 sm:items-center">
                    <Image
                      src="/begin/generated/chalk-bonus-lightbulb.png"
                      alt="Bonus"
                      width={512}
                      height={512}
                      className="mt-1 h-12 w-12 shrink-0 object-contain sm:mt-0 sm:h-14 sm:w-14 lg:hidden"
                    />
                    <h3
                      className={`${emphasisFontClassName} text-[2rem] leading-none text-white sm:text-5xl`}
                    >
                      One more thing...
                    </h3>
                  </div>
                  <p className="text-xl leading-8 text-white sm:text-2xl sm:leading-9">
                    Oh, and I&apos;m five minutes away from OpenAI&apos;s
                    Mission Bay office. I can come into the office to chat,
                    record, and attend events. 😉
                  </p>
                  <figure className="mx-auto mt-10 w-full max-w-2xl">
                    <Image
                      src="/begin/michelle-photos/michelle-at-openai-office.jpeg"
                      alt="Michelle Lawson with Jason and Romaine at OpenAI's Mission Bay office"
                      width={886}
                      height={886}
                      className="mx-auto h-auto w-full object-cover lg:max-h-[56vh] lg:w-auto"
                      sizes="(min-width: 1024px) 640px, (min-width: 640px) 75vw, calc(100vw - 48px)"
                    />
                    <figcaption className="mt-3 text-center text-sm text-white/55">
                      At OpenAI&apos;s Mission Bay office.
                    </figcaption>
                  </figure>
                </div>
              </div>
            </div>
          </div>

          <ScrollScrubVideo />

          <div
            id="the-proposal"
            className={`scroll-mt-20 max-w-4xl space-y-10 pt-14 text-xl leading-9 text-white/72 ${""}`}
          >
            <h2
              className={`${emphasisFontClassName} text-5xl font-normal leading-none tracking-tight text-white sm:text-8xl`}
            >
              {"What I’m Proposing"}
            </h2>

            <div className="space-y-7">
              <p className="mx-auto max-w-5xl text-center text-2xl leading-9 sm:text-4xl sm:leading-tight">
                <strong className="text-white">
                  {
                    "A three-year program to educate Gen Z on ways to use ChatGPT in daily life."
                  }
                </strong>
              </p>
              <p
                className={`${emphasisFontClassName} text-center text-4xl leading-none text-white sm:text-5xl`}
              >
                {"100 practical ChatGPT use cases every year."}
              </p>

              <p>
                {
                  "You're creating more useful features than any single launch campaign can fully explain."
                }
              </p>
              <p>
                I will help Gen Z understand what your features can do for them
                with one practical use case at a time.
              </p>
              <p>
                {
                  "Together, we can create an ongoing educational series that turns new and existing OpenAI capabilities into habit-building, practical how-to videos that people can understand, remember, and try."
                }
              </p>
            </div>

            {
              <div className="space-y-12">
                <div className="relative left-1/2 w-[min(76rem,calc(100vw-3rem))] -translate-x-1/2 space-y-9 py-6 sm:py-10">
                  <div className="space-y-3 text-center">
                    <h3
                      className={`${emphasisFontClassName} text-5xl leading-none text-white sm:text-7xl`}
                    >
                      How will this work?
                    </h3>
                    <p className="text-xl font-semibold text-white/78 sm:text-2xl">
                      Test. Learn. Scale what works.
                    </p>
                  </div>

                  <div className="grid gap-12 md:grid-cols-3 md:gap-5">
                    {proposalTimelineStages.map((stage, stageIndex) => (
                      <article
                        key={stage.title}
                        className="group relative min-w-0 px-2 md:px-7"
                      >
                        {stageIndex > 0 && (
                          <>
                            <Image
                              aria-hidden="true"
                              src="/begin/generated/chalk-timeline-divider.png"
                              alt=""
                              width={18}
                              height={700}
                              className="absolute -left-2.5 top-0 hidden h-full w-2 object-fill opacity-65 md:block"
                            />
                            <Image
                              aria-hidden="true"
                              src="/begin/generated/chalk-timeline-ticks.png"
                              alt=""
                              width={1200}
                              height={220}
                              className="mb-8 h-7 w-full object-fill opacity-70 contrast-125 brightness-125 md:hidden"
                            />
                          </>
                        )}

                        <div className="flex items-center gap-4">
                          <span
                            className={`${emphasisFontClassName} flex h-12 w-12 shrink-0 items-center justify-center bg-[url('/begin/generated/chalk-nav-circle.png')] bg-contain bg-center bg-no-repeat text-2xl leading-none text-white`}
                          >
                            {stage.step}
                          </span>
                          <div
                            aria-hidden="true"
                            className="h-7 min-w-0 flex-1 overflow-hidden"
                          >
                            <Image
                              src="/begin/generated/chalk-timeline-ticks.png"
                              alt=""
                              width={1200}
                              height={220}
                              className={`h-full w-full object-fill opacity-[0.72] contrast-125 brightness-125 transition-opacity duration-300 group-hover:opacity-95 ${
                                stageIndex === 1
                                  ? "scale-x-[-1]"
                                  : stageIndex === 2
                                    ? "scale-x-[0.97]"
                                    : ""
                              }`}
                            />
                          </div>
                        </div>

                        <h4
                          className={`${emphasisFontClassName} mt-6 text-4xl leading-none text-white sm:text-5xl`}
                        >
                          {stage.title}
                        </h4>
                        <p className="mt-2 text-sm font-semibold uppercase tracking-[0.16em] text-white/58">
                          {stage.duration}
                        </p>
                        <ul className="mt-5 space-y-3 text-lg leading-7 text-white/68">
                          {stage.bullets.map((bullet) => (
                            <li key={bullet} className="flex gap-3">
                              <span
                                aria-hidden="true"
                                className="mt-[0.45rem] h-3.5 w-3.5 shrink-0 bg-[url('/begin/generated/chalk-nav-circle.png')] bg-contain bg-center bg-no-repeat opacity-70"
                              />
                              <span>{bullet}</span>
                            </li>
                          ))}
                        </ul>
                      </article>
                    ))}
                  </div>
                </div>

                <section
                  aria-labelledby="projection-heading"
                  className="relative left-1/2 w-[min(76rem,calc(100vw-3rem))] -translate-x-1/2 py-4 sm:py-8"
                >
                  <div className="space-y-3 text-center">
                    <h3
                      id="projection-heading"
                      className={`${emphasisFontClassName} text-5xl leading-none text-white sm:text-7xl`}
                    >
                      What could this achieve?
                    </h3>
                    <p className="text-lg text-white/68 sm:text-xl">
                      Annual planning projections for 100 practical use cases.
                    </p>
                  </div>

                  <div className="mt-12 overflow-x-auto px-4 pb-2 sm:overflow-visible sm:px-16">
                    <table className="w-full min-w-[860px] table-fixed border-collapse text-left">
                      <colgroup>
                        <col className="w-[31%]" />
                        <col className="w-[23%]" />
                        <col className="w-[23%]" />
                        <col className="w-[23%]" />
                      </colgroup>
                      <thead>
                        <tr className="bg-[url('/begin/generated/chalk-timeline-ticks.png')] bg-[length:100%_9px] bg-bottom bg-no-repeat">
                          <th className="px-5 pb-8 align-bottom text-sm font-semibold uppercase tracking-[0.16em] text-white/48">
                            Projection metric
                          </th>
                          {["Conservative", "Expected", "Breakout"].map(
                            (scenario) => (
                              <th
                                key={scenario}
                                className="relative px-3 pb-8 text-center"
                              >
                                <span className="relative block px-3 py-5 text-xl font-semibold text-white sm:text-2xl">
                                  <span
                                    aria-hidden="true"
                                    className="pointer-events-none absolute inset-0 bg-[url('/begin/generated/chalk-card-border.png')] bg-[length:100%_100%] bg-center bg-no-repeat opacity-70"
                                  />
                                  <span className="relative z-10">
                                    {scenario}
                                  </span>
                                </span>
                              </th>
                            ),
                          )}
                        </tr>
                      </thead>
                      <tbody>
                        {projectionScenarios.map((row, index) => (
                          <tr
                            key={row.metric}
                            className={
                              index < projectionScenarios.length - 1
                                ? "bg-[url('/begin/generated/chalk-timeline-ticks.png')] bg-[length:100%_7px] bg-bottom bg-no-repeat"
                                : ""
                            }
                          >
                            <th
                              scope="row"
                              className="relative px-5 py-7 text-lg font-semibold leading-7 text-white sm:text-xl"
                            >
                              <span className="flex items-center gap-2">
                                <span>{row.metric}</span>
                                <span className="group/metric-tip relative inline-flex shrink-0">
                                  <button
                                    type="button"
                                    aria-label={`Define ${row.metric}`}
                                    aria-describedby={`projection-definition-${index}`}
                                    className="inline-flex h-5 w-5 cursor-help items-center justify-center rounded-full border border-white/30 text-white/60 outline-none transition-colors hover:border-white/70 hover:text-white focus-visible:border-white focus-visible:text-white"
                                  >
                                    <Info
                                      aria-hidden="true"
                                      className="h-3 w-3"
                                    />
                                  </button>
                                  <span
                                    id={`projection-definition-${index}`}
                                    role="tooltip"
                                    className="pointer-events-none absolute bottom-full left-0 z-50 mb-3 w-80 translate-y-1 p-5 text-left text-sm font-normal leading-6 text-white opacity-0 shadow-2xl transition-all duration-200 group-hover/metric-tip:translate-y-0 group-hover/metric-tip:opacity-100 group-focus-within/metric-tip:translate-y-0 group-focus-within/metric-tip:opacity-100"
                                  >
                                    <span
                                      aria-hidden="true"
                                      className="absolute inset-0 bg-black/95 bg-[url('/begin/generated/chalk-card-border.png')] bg-[length:100%_100%] bg-center bg-no-repeat"
                                    />
                                    <span className="relative z-10 block px-1 py-0.5">
                                      {row.definition}
                                    </span>
                                  </span>
                                </span>
                              </span>
                              {row.northStar && (
                                <span className="mt-1 block text-xs font-semibold uppercase tracking-[0.16em] text-white/48">
                                  North-star metric
                                </span>
                              )}
                            </th>
                            {[
                              {
                                value: row.conservative,
                                calculation: row.calculations.conservative,
                              },
                              {
                                value: row.expected,
                                calculation: row.calculations.expected,
                              },
                              {
                                value: row.breakout,
                                calculation: row.calculations.breakout,
                              },
                            ].map(({ value, calculation }, valueIndex) => (
                                <td
                                  key={`${row.metric}-${valueIndex}`}
                                  className="relative px-4 py-7 text-center text-3xl font-semibold leading-none text-white sm:text-4xl"
                                >
                                  <span
                                    aria-hidden="true"
                                    className="pointer-events-none absolute -left-1 top-2 h-[calc(100%-1rem)] w-2 bg-[url('/begin/generated/chalk-timeline-divider.png')] bg-[length:100%_100%] bg-center bg-no-repeat opacity-30"
                                  />
                                  <span className="group/cell-tip relative inline-flex">
                                    <button
                                      type="button"
                                      aria-label={`Explain the ${value} ${row.metric} calculation`}
                                      aria-describedby={`projection-calculation-${index}-${valueIndex}`}
                                      className="cursor-help rounded-sm outline-none focus-visible:ring-1 focus-visible:ring-white/70"
                                    >
                                      <CountUpMetric
                                        value={value}
                                        delayMs={index * 55 + valueIndex * 70}
                                      />
                                    </button>
                                    <span
                                      id={`projection-calculation-${index}-${valueIndex}`}
                                      role="tooltip"
                                      className="pointer-events-none absolute bottom-full left-1/2 z-50 mb-2 w-64 -translate-x-1/2 translate-y-1 p-4 text-left text-sm font-normal leading-6 text-white opacity-0 shadow-2xl transition-all duration-200 group-hover/cell-tip:translate-y-0 group-hover/cell-tip:opacity-100 group-focus-within/cell-tip:translate-y-0 group-focus-within/cell-tip:opacity-100"
                                    >
                                      <span
                                        aria-hidden="true"
                                        className="absolute inset-0 bg-black/95 bg-[url('/begin/generated/chalk-card-border.png')] bg-[length:100%_100%] bg-center bg-no-repeat"
                                      />
                                      <span className="relative z-10 block px-1 py-0.5">
                                        {calculation}
                                      </span>
                                    </span>
                                  </span>
                                </td>
                              ))}
                          </tr>
                        ))}
                      </tbody>
                    </table>
                  </div>

                  <p className="mx-auto mt-5 max-w-4xl text-center text-sm leading-6 text-white/50 sm:text-base">
                    These are planning scenarios, not guarantees. Final targets
                    and measurement methods will be agreed during Discussion.
                  </p>
                </section>

                <div className="space-y-5">
                  <p className="text-2xl font-semibold leading-8 text-white sm:text-3xl sm:leading-10">
                    What this gives you:
                  </p>
                  <div className="grid gap-4 sm:grid-cols-2">
                    {proposalPayoffs.map(
                      ({ title, description, Icon }, index) => (
                        <div
                          key={title}
                          className="group relative min-h-56 p-8 sm:p-9"
                        >
                          <span
                            aria-hidden="true"
                            className={`pointer-events-none absolute inset-0 bg-[url('/begin/generated/chalk-card-border.png')] bg-[length:100%_100%] bg-center bg-no-repeat opacity-65 transition-[opacity,transform] duration-300 group-hover:scale-[1.01] group-hover:opacity-95 ${
                              index % 2 === 0
                                ? "-rotate-[0.3deg]"
                                : "rotate-[0.3deg]"
                            }`}
                          />
                          <div className="relative z-10 mb-5 flex h-12 w-12 items-center justify-center bg-[url('/begin/generated/chalk-nav-circle.png')] bg-contain bg-center bg-no-repeat opacity-85 transition-transform duration-300 group-hover:-rotate-6 group-hover:scale-105">
                            <Icon
                              aria-hidden="true"
                              className="h-5 w-5 text-white"
                              strokeWidth={1.8}
                            />
                          </div>
                          <h3 className="relative z-10 text-xl font-semibold leading-7 text-white sm:text-2xl">
                            {title}
                          </h3>
                          <p className="relative z-10 mt-3 text-lg leading-8 text-white/68">
                            {description}
                          </p>
                        </div>
                      ),
                    )}
                  </div>
                </div>
              </div>
            }

            <div className="space-y-7">
              <p>
                {
                  "Every year, I will turn 100 practical ChatGPT use cases into education Gen Z can understand, remember, and try."
                }
              </p>
              <p className="text-white">
                {
                  "With me as your dedicated educator and ambassador to Gen Z, more people will understand what ChatGPT can do, see themselves in the use case, try it once, and build the habit of coming back."
                }
              </p>
            </div>
          </div>

          <div
            id="chatgpt-videos"
            className={`scroll-mt-20 max-w-5xl pt-14 ${""}`}
          >
            <h2
              className={`${emphasisFontClassName} text-5xl font-normal leading-none tracking-tight text-white sm:text-8xl`}
            >
              {"100 ChatGPT Use Cases I Could Teach in the Next Year"}
            </h2>

            <div className="mt-14 space-y-10">
              {chatGPTUseCaseFeatures.map((feature) => (
                <div
                  key={feature.feature}
                  className="grid items-start gap-4 sm:grid-cols-[minmax(10rem,0.7fr)_6rem_minmax(0,1.3fr)] sm:gap-8"
                >
                  <div className="relative h-16 w-full sm:h-24">
                    {feature.featureImage ? (
                      <Image
                        src={feature.featureImage}
                        alt={feature.feature}
                        fill
                        className="object-contain object-left"
                        sizes="(min-width: 1024px) 280px, (min-width: 640px) 34vw, 90vw"
                      />
                    ) : (
                      <p
                        className={`${emphasisFontClassName} text-4xl leading-none text-white sm:text-5xl`}
                      >
                        {feature.feature}
                      </p>
                    )}
                  </div>

                  <div className="relative ml-3 h-10 w-20 rotate-90 sm:ml-0 sm:mt-2 sm:h-16 sm:w-full sm:rotate-0">
                    <Image
                      src="/begin/chalk-arrow-right.png"
                      alt=""
                      fill
                      aria-hidden="true"
                      className="object-contain"
                      sizes="112px"
                    />
                  </div>

                  <ul className="space-y-3 text-xl leading-8 text-white/72">
                    {feature.useCases.map((useCase) => (
                      <li key={useCase} className="flex gap-3">
                        <span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-white/70" />
                        <span>{useCase}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>

            <div className="mt-16 grid items-start gap-4 sm:grid-cols-[minmax(10rem,0.7fr)_6rem_minmax(0,1.3fr)] sm:gap-8">
              <div className="relative h-16 w-full sm:h-24">
                <Image
                  src="/begin/releases-generated/new-feature-question-v2.png"
                  alt="Two question marks above the words new feature written in chalk"
                  fill
                  className="object-contain object-left mix-blend-screen"
                  sizes="(min-width: 1024px) 360px, (min-width: 640px) 36vw, 90vw"
                />
              </div>

              <div className="relative ml-3 h-10 w-20 rotate-90 sm:ml-0 sm:mt-2 sm:h-16 sm:w-full sm:rotate-0">
                <Image
                  src="/begin/chalk-arrow-right.png"
                  alt=""
                  fill
                  aria-hidden="true"
                  className="object-contain"
                  sizes="112px"
                />
              </div>

              <p className="flex gap-3 text-xl leading-8 text-white/72">
                <span className="mt-3 h-1.5 w-1.5 shrink-0 rounded-full bg-white/70" />
                <span>
                  Let&apos;s discuss which new features matter most and turn
                  them into practical use cases people can try.
                </span>
              </p>
            </div>
          </div>

          <div
            id="lets-talk"
            className={`scroll-mt-20 mt-14 space-y-5 text-white sm:mt-20 sm:space-y-6 ${""}`}
          >
            <p
              className={`${emphasisFontClassName} text-5xl leading-none sm:text-7xl`}
            >
              {"That's the first 12."}
            </p>
            <p className="text-2xl leading-9 text-white/72 sm:text-3xl sm:leading-10">
              {"Want to see the next 88? Let's talk!"}
            </p>

            <div className="flex justify-center pt-6 sm:pt-10">
              <a
                href={emailTeamHref}
                className="begin-email-team-button"
                aria-label={`Email Michelle, Patrick, and Teresa about the ${"OpenAI"} partnership`}
              />
            </div>
          </div>

          <footer className={`pt-24 text-center text-base text-white/48 ${""}`}>
            {"This webpage was made with Codex 😉"}
          </footer>
        </div>
      </section>
    </main>
  );
}
