/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type VideoEmbed = {
  _type: "videoEmbed";
  url?: string;
  title?: string;
  shape?: "landscape" | "portrait" | "square";
  caption?: string;
  transcript?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  keywords?: Array<string>;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Resource = {
  _type: "resource";
  title?: string;
  url?: string;
  description?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question?: string;
  answer?: string;
};

export type Code = {
  _type: "code";
  language?: string;
  code?: string;
};

export type Callout = {
  _type: "callout";
  tone?: "tip" | "important" | "action";
  title?: string;
  text?: string;
};

export type ArticleImage = {
  _type: "articleImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
};

export type ArticleReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "article";
};

export type ArticleLike = {
  _id: string;
  _type: "articleLike";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  article?: ArticleReference;
  visitorHash?: string;
  likedAt?: string;
};

export type Comment = {
  _id: string;
  _type: "comment";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  article?: ArticleReference;
  displayName?: string;
  emailHash?: string;
  message?: string;
  status?: "pending" | "approved" | "rejected";
  submittedAt?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type Article = {
  _id: string;
  _type: "article";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  dek?: string;
  coverImage?: ArticleImage;
  author?: AuthorReference;
  publishedAt?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    _key: string;
  } & ArticleImage | {
    _key: string;
  } & Callout | {
    _key: string;
  } & Code | {
    _key: string;
  } & VideoEmbed>;
  resources?: Array<{
    _key: string;
  } & Resource>;
  faq?: Array<{
    _key: string;
  } & FaqItem>;
  category?: "ai" | "career" | "college" | "building" | "life";
  topics?: Array<string>;
  featured?: boolean;
  seo?: Seo;
  readerQuestion?: string;
  sourceUrl?: string;
  sourceTranscript?: string;
  editorialNotes?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  bio?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = VideoEmbed | SanityImageAssetReference | Seo | Resource | FaqItem | Code | Callout | ArticleImage | ArticleReference | ArticleLike | Comment | AuthorReference | Article | SanityImageCrop | SanityImageHotspot | Slug | Author | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;

// Source: ../personal-website/sanity/lib/queries.ts
// Variable: ARTICLES_QUERY
// Query: *[_type == "article" && defined(slug.current) && defined(publishedAt)]  | order(featured desc, publishedAt desc) {      _id,  title,  dek,  "slug": slug.current,  publishedAt,  category,  topics,  featured,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "author": author->{name, role, "imageUrl": image.asset->url, "imageAlt": image.alt},  "estimatedWords": round(length(pt::text(body)) / 5)  }
export type ARTICLES_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  dek: string | null;
  slug: string | null;
  publishedAt: string | null;
  category: "ai" | "building" | "career" | "college" | "life" | null;
  topics: Array<string> | null;
  featured: boolean | null;
  coverImageUrl: string | null;
  coverImageAlt: string | null;
  author: {
    name: string | null;
    role: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
  } | null;
  estimatedWords: number;
}>;

// Source: ../personal-website/sanity/lib/queries.ts
// Variable: ARTICLE_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {      _id,  title,  dek,  "slug": slug.current,  publishedAt,  category,  topics,  featured,  "coverImageUrl": coverImage.asset->url,  "coverImageAlt": coverImage.alt,  "author": author->{name, role, "imageUrl": image.asset->url, "imageAlt": image.alt},  "estimatedWords": round(length(pt::text(body)) / 5),    body[]{..., asset->{url}},    resources,    faq,    sourceUrl,    seo,    "comments": *[_type == "comment" && article._ref == ^._id && status == "approved"] | order(submittedAt desc) {      _id,      displayName,      message,      submittedAt    },    "likeCount": count(*[_type == "articleLike" && article._ref == ^._id])  }
export type ARTICLE_QUERY_RESULT = {
  _id: string;
  title: string | null;
  dek: string | null;
  slug: string | null;
  publishedAt: string | null;
  category: "ai" | "building" | "career" | "college" | "life" | null;
  topics: Array<string> | null;
  featured: boolean | null;
  coverImageUrl: string | null;
  coverImageAlt: string | null;
  author: {
    name: string | null;
    role: string | null;
    imageUrl: string | null;
    imageAlt: string | null;
  } | null;
  estimatedWords: number;
  body: Array<{
    _key: string;
    _type: "articleImage";
    asset: {
      url: string | null;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
  } | {
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h2" | "h3" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      blank?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
    asset: null;
  } | {
    _key: string;
    _type: "callout";
    tone?: "action" | "important" | "tip";
    title?: string;
    text?: string;
    asset: null;
  } | {
    _key: string;
    _type: "code";
    language?: string;
    code?: string;
    asset: null;
  } | {
    _key: string;
    _type: "videoEmbed";
    url?: string;
    title?: string;
    shape?: "landscape" | "portrait" | "square";
    caption?: string;
    transcript?: string;
    asset: null;
  }> | null;
  resources: Array<{
    _key: string;
  } & Resource> | null;
  faq: Array<{
    _key: string;
  } & FaqItem> | null;
  sourceUrl: string | null;
  seo: Seo | null;
  comments: Array<{
    _id: string;
    displayName: string | null;
    message: string | null;
    submittedAt: string | null;
  }>;
  likeCount: number;
} | null;

// Source: ../personal-website/sanity/lib/queries.ts
// Variable: ARTICLE_METADATA_QUERY
// Query: *[_type == "article" && slug.current == $slug][0] {    title,    dek,    "slug": slug.current,    publishedAt,    _updatedAt,    category,    topics,    "coverImageUrl": coalesce(seo.image.asset->url, coverImage.asset->url),    "seoTitle": seo.title,    "seoDescription": seo.description,    "noIndex": seo.noIndex,    "authorName": author->name  }
export type ARTICLE_METADATA_QUERY_RESULT = {
  title: string | null;
  dek: string | null;
  slug: string | null;
  publishedAt: string | null;
  _updatedAt: string;
  category: "ai" | "building" | "career" | "college" | "life" | null;
  topics: Array<string> | null;
  coverImageUrl: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  noIndex: boolean | null;
  authorName: string | null;
} | null;

// Source: ../personal-website/sanity/lib/queries.ts
// Variable: ARTICLE_SLUGS_QUERY
// Query: *[_type == "article" && defined(slug.current)][]{"slug": slug.current}
export type ARTICLE_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../personal-website/sanity/lib/queries.ts
// Variable: SITEMAP_ARTICLES_QUERY
// Query: *[_type == "article" && defined(slug.current) && coalesce(seo.noIndex, false) != true][]{    "slug": slug.current,    "lastModified": coalesce(_updatedAt, publishedAt)  }
export type SITEMAP_ARTICLES_QUERY_RESULT = Array<{
  slug: string | null;
  lastModified: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"article\" && defined(slug.current) && defined(publishedAt)]\n  | order(featured desc, publishedAt desc) {\n    \n  _id,\n  title,\n  dek,\n  \"slug\": slug.current,\n  publishedAt,\n  category,\n  topics,\n  featured,\n  \"coverImageUrl\": coverImage.asset->url,\n  \"coverImageAlt\": coverImage.alt,\n  \"author\": author->{name, role, \"imageUrl\": image.asset->url, \"imageAlt\": image.alt},\n  \"estimatedWords\": round(length(pt::text(body)) / 5)\n\n  }\n": ARTICLES_QUERY_RESULT;
    "\n  *[_type == \"article\" && slug.current == $slug][0] {\n    \n  _id,\n  title,\n  dek,\n  \"slug\": slug.current,\n  publishedAt,\n  category,\n  topics,\n  featured,\n  \"coverImageUrl\": coverImage.asset->url,\n  \"coverImageAlt\": coverImage.alt,\n  \"author\": author->{name, role, \"imageUrl\": image.asset->url, \"imageAlt\": image.alt},\n  \"estimatedWords\": round(length(pt::text(body)) / 5)\n,\n    body[]{..., asset->{url}},\n    resources,\n    faq,\n    sourceUrl,\n    seo,\n    \"comments\": *[_type == \"comment\" && article._ref == ^._id && status == \"approved\"] | order(submittedAt desc) {\n      _id,\n      displayName,\n      message,\n      submittedAt\n    },\n    \"likeCount\": count(*[_type == \"articleLike\" && article._ref == ^._id])\n  }\n": ARTICLE_QUERY_RESULT;
    "\n  *[_type == \"article\" && slug.current == $slug][0] {\n    title,\n    dek,\n    \"slug\": slug.current,\n    publishedAt,\n    _updatedAt,\n    category,\n    topics,\n    \"coverImageUrl\": coalesce(seo.image.asset->url, coverImage.asset->url),\n    \"seoTitle\": seo.title,\n    \"seoDescription\": seo.description,\n    \"noIndex\": seo.noIndex,\n    \"authorName\": author->name\n  }\n": ARTICLE_METADATA_QUERY_RESULT;
    "\n  *[_type == \"article\" && defined(slug.current)][]{\"slug\": slug.current}\n": ARTICLE_SLUGS_QUERY_RESULT;
    "\n  *[_type == \"article\" && defined(slug.current) && coalesce(seo.noIndex, false) != true][]{\n    \"slug\": slug.current,\n    \"lastModified\": coalesce(_updatedAt, publishedAt)\n  }\n": SITEMAP_ARTICLES_QUERY_RESULT;
  }
}
